### ISSUE TITLE
Some needles/callbacks are not working

### ISSUE THREAD

**Issue by atomfrede** [jhipster/jhipster-vuejs#132] opened 2018-12-18 10:46 UTC
While I was working on integrating moment webpack plugin I came across a problem when some callbacks are executed (in https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/utils.js). So on the current master branch there is `addLanguagesToWebPackConfiguration` not correctly executed. The second failure comes from a callback that is executed in the main generator (and we don't have such a file in our setup). 

So basically I was not able to add the selected languages to the webpack config as we do for angular/react. Not sure if this a problem of the vue blueprint or a more general problem. 

```
Unable to find webpack/webpack.dev.js or missing required jhipster-needle. Webpack language task not updated with languages: en,de since block was not found. Check if you have enabled translation support.


Unable to find src/main/webapp//app/config/translation.ts or missing required jhipster-needle. Language pipe not updated with languages: en,de since block was not found. Check if you have enabled translation support.
```

**Comment by pascalgrimaud** [comment] 2018-12-21 08:18
All needles need to be checked:
- if you regenerate an entity, the needle will add again the same code, so there will be duplicated code which will fail during compilation

**Comment by atomfrede** [comment] 2019-01-02 09:31
Yes somehow I think. According to our documentation a blueprint can not overwrite the language subgen. The needles are executed during normal creation of an application and are not working (at least ypu see the errors on the console).

**Comment by pascalgrimaud** [comment] 2019-01-02 09:42
@atomfrede : when I used `jhipster languages --blueprint vuejs`, I don't have error, but the new language is not added to `config.ts` file. Do you have all steps to reproduce ?

I think all blueprint should allow to overwrite language subgen.
@murdos : are you OK with that ? If yes, I'll start to update languages+blueprint

**Comment by atomfrede** [comment] 2019-01-02 09:53
@pascalgrimaud Let me check later when I am back home. But I got that error when just creating an app with the vue blueprint. Will check if its still the case with the current master.

**Comment by pascalgrimaud** [comment] 2019-01-02 09:56
Okey, nothing urgent @atomfrede 
But, I wonder if it is really needed to add the sub module languages here, as... after discussion with Julien, we'll probably merge this blueprint into the main generator.

**Comment by atomfrede** [comment] 2019-01-02 10:56
Supporting 3 ui stacks in the main generator?

**Comment by murdos** [comment] 2019-01-02 11:21
If we support 3 ui stacks, then we need to think how to factorize some parts of the client templates.
There's already some duplicated content that makes maintenance more difficult.

**Comment by atomfrede** [comment] 2019-01-02 13:00
At the moment I would not go to merge it into the main generator

**Comment by pascalgrimaud** [comment] 2019-01-02 13:09
No worry, if it will be merged, it will be done in few months, not now.
I just said that because Julien said us he wants VueJS in main generator :dancer:

**Comment by atomfrede** [comment] 2019-01-02 13:37
Ah in a few month, all good :heavy_check_mark:

**Comment by murdos** [comment] 2019-01-03 08:55
While I agree that this would be a perfect occasion to improve blueprint system and keep code modular, I see a big issue with turning vuejs as a blueprint: since you can't use multiple blueprints, using vuejs blueprint would prevent the user to use any other blueprint (e.g. kotlin or any enterprise blueprint).

**Comment by pascalgrimaud** [comment] 2019-01-03 08:57
you're right @murdos ; for now, we can't use multiple blueprint

**Comment by murdos** [comment] 2019-01-04 13:05
>
> I think all blueprint should allow to overwrite language subgen.
> @murdos : are you OK with that ? If yes, I'll start to update languages+blueprint

@pascalgrimaud Sorry, I just saw this message. Yes, allowing overriding the `languages` subgen in blueprint sounds logicial, and I think it has already been requested. Do you plan to do it or should I look at it?

**Comment by pascalgrimaud** [comment] 2019-01-04 13:09
I already have done the generator-jhipster part, but only locally, and started the blueprint generator this morning. I didn't push any code yet.

I'll request your help/review in severals PR as soon as it's finished.

**Closed** 2019-01-17 09:07 UTC
Labels: $100, bug

**Comment by pascalgrimaud** [comment] 2019-01-24 12:09
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/6583
