### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by pradeepachan** [jhipster/jhipster-vuejs#10] opened 2018-09-18 21:18 UTC
From the README
jhipster -d --blueprint vuejs
Seems to give error.

Instead: 
jhipster -d --blueprint generator-jhipster-vuejs 
Worked for me. 

If it is an error in the README, please update.

**Comment by deepu105** [comment] 2018-09-19 07:01
No its not a Readme error, both should work. Need to chek this

**Comment by deepu105** [comment] 2018-09-19 07:28
Which version of JHipster are you using?  it works fine for me with latest master of this repo and latest JHipster. I cannot reproduce so closing this. If you have more info update me

**Closed by deepu105** 2018-09-19 07:28 UTC
