### ISSUE TITLE
Infinite-scroll pagination not generated

### ISSUE THREAD

**Issue by HJK181** [jhipster/jhipster-vuejs#537] opened 2020-01-30 06:51 UTC
##### **Overview of the issue**

The pagination option `infinite-scroll` does not have any effect.

##### **Reproduce the error**

First create the application via `jhipster --blueprints vuejs`, than run either `jhipster import-jdl some-entities.jdl` or `jhipster entity Picture`.

##### **JHipster Version(s)**

```
gateway@0.0.0 C:\foo\bar\gateway
`-- generator-jhipster-vuejs@1.3.0
  `-- generator-jhipster@6.5.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.foo",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "de.fo",
    "packageFolder": "de/foo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "cool",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1580197134739,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.3.0"
      }
    ],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en"
    ],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.3.0"
      }
    ]
  },
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.5.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "materia",
    "clientThemeVariant": "light"
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Picture.json
```
{
    "name": "Picture",
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 150
        },
        {
            "fieldName": "uri",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "visibility",
            "fieldType": "Visibility",
            "fieldValues": "ALL,PACK,NONE",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "approved",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "data",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "relationships": [],
    "changelogDate": "20200129073108",
    "javadoc": "The Picture entity.\\n@author hjk",
    "entityTableName": "picture",
    "dto": "no",
    "pagination": "infinite-scroll",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "readOnly": false,
    "clientRootFolder": "",
    "applications": "*"
}
```

##### **Browsers and Operating System**

-   [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by HJK181** [comment] 2020-01-30 07:31
Updated to newest `1.4.0` release, with the same outcome.

**Comment by pascalgrimaud** [comment] 2020-02-09 13:55
Confirmed the issue
I wanted to do a new release of Vue.js but this one should be easy to fix, so I postpone the release, so if someone want to fix this ?

**Comment by pascalgrimaud** [comment] 2020-02-09 16:14
I'm changing the label as in fact, it's not a bug. It's simply something which was not implemented initialy.

**Comment by skmaingi** [comment] 2020-02-14 21:58
I'm using Vue-infinite-loading plugin. 

**Installation** 

npm install vue-infinite-loading --save

**Usage**
Insert

```
                <infinite-loading
                    v-if="entityarray && entityarray.length > 0 && links != {} && page < links['last']"
                    :identifier="infiniteId"
                    slot="append"
                    @infinite="loadPage"
                    force-use-infinite-wrapper=".el-table__body-wrapper"
                    :distance='50'>
                    <template slot="no-more">No more data</template>
                </infinite-loading>

```

before table closing tag "</table"

**JhiDataUtils method to parse header links to get maximum loading count**

```
  parseLinks(header) {
    if (header.length === 0) {
      throw new Error('input must not be of zero length');
    }

    // Split parts by comma
    var parts = header.split(',');
    var links = {};
    // Parse each part into a named link
    parts.forEach((p) => {
      var section = p.split('>;');
      if (section.length !== 2) {
        throw new Error('section could not be split on ">;"');
      }
      var url = section[0].replace(/<(.*)/, '$1').trim();
      var queryString = {page:null};
      url.replace(
        new RegExp('([^?=&]+)(=([^&]*))?', 'g'),
        function($0, $1, $2, $3) { queryString[$1] = $3; }
      );
      var page = queryString.page;
      if (typeof page  == 'string') {
        page = parseInt(page);
      }
      var name = section[1].replace(/rel="(.*)"/, '$1').trim();
      links[name] = page;
    });
    return links;
  }
```

**Entity component changes**

Changes in entity service _then_ callback function

```
          for (var i = 0; i < res.data.length; i++) {
            this.entityarray.push(res.data[i]);
          }
          this.totalItems = Number(res.headers['x-total-count']);
          this.links = this.parseLinks(res.headers.link);
          this.isFetching = false;
          if(this.state != null) {
            this.state.loaded();
            if(this.page == this.links['last'])
              this.state.complete();
          }

```

Method load next page on scrolling

```
  public loadPage($state): void {
    this.state = $state;
    if(this.page >= this.links['last'])
      this.state.complete();
    if(!this.isFetching) {
      this.page++;
      this.retrieveAllEntities();
    }
  }
```

**Comment by skmaingi** [comment] 2020-02-14 22:40
@pascalgrimaud is the bug-bounty still there? I'm in dire need of funding for my 4 social projects.
1. [mispers](http://mispers.org): Project to find missing persons
2. [mfadhili](http://mfadhili.org): (Swahili: donor) platform to help patients get blood donations
3. [fichua](http://fichua.org): (Swahili: expose) Whistleblowers platform
4. [itracker CE](https://itrackercommunity.herokuapp.com): Platform to track incidents such as locusts invasion and coronavirus

**Comment by pascalgrimaud** [comment] 2020-02-15 06:21
@skmaingi : yes, the bounty is still there. You seem to know how to fix it, so would you like to contribute ?
Don't hesitate to ask me if you need help

**Comment by skmaingi** [comment] 2020-02-15 15:06
@pascalgrimaud yes, I would like to contribute.

**Comment by skmaingi** [comment] 2020-02-15 17:53
@pascalgrimaud I need access to commit the code for infinite-scroll feature

**Comment by pascalgrimaud** [comment] 2020-02-15 17:58
@skmaingi : for contributing to Open Source project, you need:
- fork this project
- clone your fork locally: `git clone https://github.com/skmaingi/jhipster-vuej`
- go into your fork locally, add upstream: `git remote add upstream https://github.com/jhipster/jhipster-vuej`
- develop the fix
- then, the most important part: `git push origin <your branch>` -> so you'll push to your fork and not to main project
- so in GitHub, you'll be able to submit the pull request

**Comment by skmaingi** [comment] 2020-02-16 01:41
@pascalgrimaud : I have added the new feature.

The v-if directive in _infinite-loading_ component is optional. One can omit it to display the component's template if there is no more data to load.

**Comment by pascalgrimaud** [comment] 2020-02-16 07:58
@skmaingi : nice ! waiting your pull request so we can review :)

**Comment by pascalgrimaud** [comment] 2020-02-20 05:22
@skmaingi : I'm increasing the bounty as I saw you spent a lot of time to achieve your 1st contribution to the project, so it is well deserved !

**Closed** 2020-02-20 05:23 UTC
Labels: $$ bug-bounty $$, $200, feature request

**Comment by skmaingi** [comment] 2020-02-20 08:48
@pascalgrimaud Thank you so much
