### ISSUE TITLE
 user-management.component.ts TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by kentkwan** [jhipster/jhipster-vuejs#484] opened 2019-10-16 07:56 UTC
##### **Overview of the issue**

Comile user-management.component.ts.

Got “TS2345: Argument of type 'number' is not assignable to parameter of type 'string'”.

##### **Motivation for or Use Case**

Compile error.

##### **Reproduce the error**

Use " jhipster --blueprint vuejs " to create project, and then, " jhipster entity demo --blueprint vuejs" .

##### **Suggest a Fix**

No suggest.

##### **JHipster Version(s)**

```
demo@0.0.0 /Users/Kent/Desktop/jh
└─┬ generator-jhipster-vuejs@1.1.0
  └── generator-jhipster@6.1.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "demo"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "monolith",
    "baseName": "demo",
    "packageName": "demo",
    "packageFolder": "demo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.1.0"
      }
    ],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.1.0"
      }
    ]
  },
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "demo",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "none",
    "clientThemeVariant": ""
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Player {
  name String required unique minlength(4) maxlength(20),
  created ZonedDateTime required
}
dto Player with mapstruct
paginate Player with pagination
service Player with serviceClass
search Player with elasticsearch

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yarn: 1.15.2

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

macOS 10.15 with safari 13.0.2 
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Falydoor** [comment] 2019-10-16 23:02
I was not able to reproduce your issue but instead I had a different one...

Can you try with my branch https://github.com/Falydoor/jhipster-vuejs/tree/fix-websocket-test-without-i18n ?

You will have to follow those instructions https://github.com/jhipster/jhipster-vuejs#running-local-blueprint-version-for-development in order to have my branch working locally.

**Comment by pascalgrimaud** [comment] 2019-10-18 05:29
@kentkwan : I think it was fixed since the last release. Can you try the v1.2.0 plz ?

**Comment by hdurix** [comment] 2019-12-10 14:13
Because we are not able to reproduce the problem (it seems this has been fixed), I think that's better to close this issue. Don't hesitate to re-open it if you encounter the bug again.

**Closed by hdurix** 2019-12-10 14:13 UTC
