### ISSUE TITLE
acorn and lazy loading Errors during `npm run webpack:build`

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/jhipster-vuejs#598] opened 2020-04-29 19:11 UTC
##### **Overview of the issue**

cannot find module 'acorn'

--- 

cannot find loader on line 10 in router/index.ts: 
`const Home = () => import('../core/home/home.vue');`

##### **Reproduce the error**

`jhipster --blueprint vuejs`
`mvn`

##### **Suggest a Fix**

What made the problems disappear:

npm i --save-dev acorn

change lazy loading to normal loading:

```
import Home from '../core/home/home.vue';
import Error from '../core/error/error.vue';
import JhiConfigurationComponent from '../admin/configuration/configuration.vue';
import JhiDocsComponent from '../admin/docs/docs.vue';
import JhiHealthComponent from '../admin/health/health.vue';
import JhiLogsComponent from '../admin/logs/logs.vue';
import JhiAuditsComponent from '../admin/audits/audits.vue';
import JhiMetricsComponent from '../admin/metrics/metrics.vue';
import JhiTrackerComponent from '../admin/tracker/tracker.vue';
```

##### **JHipster Version(s)**

6.8.0

##### **JHipster configuration**

.yo-rc.json

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "***"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "***",
    "packageName": "***",
    "packageFolder": "***",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "***",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "VueJS", // has no effect?
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1586208446028,
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.7.0"
      }
    ],
    "enableTranslation": false,
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.7.0"
      }
    ],
    "searchEngine": false
  }
}
```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment] 2020-05-03 20:53
I was not able to reproduce it with the current master branch.

**Comment by qmonmert** [comment] 2020-08-03 09:34
@geyuqiu same as @atomfrede I don't reproduce

**Comment by qmonmert** [comment] 2020-08-28 08:49
@pascalgrimaud & @atomfrede I think you can close this ticket

**Closed** 2020-08-28 08:56 UTC
