### ISSUE TITLE
Error Argument of type 'number' is not assignable to parameter of type 'string' in user-management.component.ts

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [jhipster/jhipster-vuejs#453] opened 2019-09-27 21:38 UTC
When running npm start it gives following error

ERROR in /src/main/webapp/app/admin/user-management/user-management.component.ts(98,15) TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

Issue is code passes integer value to the  userManagementService().remove function while it requires a string and can be fixed by simply converting it to a String like this
`this.userManagementService()
      .remove(String(this.removeId))`

**Comment by hdurix** [comment] 2019-12-10 14:25
Another issue (very close) has been created after yours: https://github.com/jhipster/jhipster-vuejs/issues/484.

I tried to reproduce the problem but this seems to have been fixed since you submitted this issue. I'm closing it, don't hesitate to re-open the ticket if you're still facing this bug.

**Closed by hdurix** 2019-12-10 14:25 UTC
