### ISSUE TITLE
Refresh an entity page is failing

### ISSUE THREAD

**Issue by fleboulch** [jhipster/jhipster-vuejs#404] opened 2019-06-25 14:44 UTC
##### **Overview of the issue**

When you press F5 on en entity page, you have the following error.
_Note: my client and server are not separated_

![image](https://user-images.githubusercontent.com/9569081/60107806-d3a8ee00-9767-11e9-9c57-db9cc211d017.png)

##### **Reproduce the error**

1. Generate an VUEJS blueprint app
2. Log in as admin or user.
3. Then go on an entity page, then do a refresh

##### **Related issues**
 
This is a regression since #388 has been added

##### **JHipster configuration**
<details><summary>.yo-rc.json</summary>
<p>

```bash
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "NDUxMzc0NjEwNDRlMjlkZjI5YjIxN2U3MWM0NzA5OGFjM2E4ZTcwNGI1NDY4MTdmNmQxNDc3YjlmZTRmZDdiZmRkMzkxYjM2ODBmODE0MmI4NzYwMzllMjY2ZGZmMTI2YjgwZTJkY2YzZTg1NGE2YjE0ZTBkZGU1NzFhY2YwYjc=",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.0.0"
      }
    ],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "fr",
    "languages": ["fr"],
    "blueprint": "generator-jhipster-vuejs",
    "blueprintVersion": "1.0.0"
  },
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.0.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "clientFramework": "vue",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm"
  }
}

```

</p>
</details>

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by fleboulch** [comment] 2019-07-05 08:24
@ruddell could you help on that?
I don't know if we have a key on the `.yo-rc.json` file to know if the client and the server are separated or not.

In my app the client and the server are not separated and to fix this I just rollback #388

**Comment by ruddell** [comment] 2019-07-05 14:47
I could not reproduce, are you sure you have `historyApiFallback: true` in your `webpack.dev.js`?  If I remove that line I see your issue, but it works fine when it is present.

**Comment by fleboulch** [comment] 2019-07-10 08:56
I will re-check on my side and close this issue if it's ok.
Thanks for the quick answer @ruddell

**Comment by atomfrede** [comment] 2019-12-02 21:44
The issue is fixed. Tried just now with the latest master branch, Will close it.

**Closed by atomfrede** 2019-12-02 21:44 UTC
Labels: bug
